### ISSUE TITLE
First sample taken on sigrok is not correct

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#23]
**What happens:**
The first received sample from ACSP to sigrok is incorrect. It seems to be random data.
**What is expected to happen:**
The first sample should be the actual sample from users device
**How to repeat:**
- plug in ACSP, turn on Sigrok PV and load ACSP driver
- Press run on Sigrok 
- Note the produced waveform is likely an unexpected one

This could be an issue with either Sigrok or ACSP. It does not show up on simulation for ACSP.

**Comment by ColePBryan** [comment]
Nevermind, the first data is not random. It is "0x41 0x43 0x53 0x50 0x41 0x43 0x53 0x50". It happens whenever the driver is loaded. If you translate it to ASCII it says "ACSPACSP". It either has that stuck in the buffer from uart or it resends some op code cause the ACSP to send its name twice. I'm pretty sure this is a Sigrok driver issue.

**Comment by ColePBryan** [comment]
This issue can also be repeated when the ACSP reset button is pressed. I'm back to thinking this is an issue with ACSP.

**Comment by alexnorell** [comment]
Fixed
