### ISSUE TITLE
Data comes in backwards on Pulseview 

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#24]
This is likely an artifact from OLS driver.

**What Happens:**
Data comes in backwards on capture (ie 0xAA -> 0x55)
This issue ends up putting the signals in reverse order (signal 0 gets signal 8's data, etc.)
**What is expected:**
Data should not be backwards, all signals should get their own data.
**How to repeat:**
Input expected signals and look at the produced waveform.

**Comment by alexnorell** [comment]
Completed
