### ISSUE TITLE
Set up trigger to work with ACSP

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#25]
Sigrok is not set up to handle triggers with ACSP:

-Currently the triggers on Sigrok are expected level sensitive, but ACSP is edge triggered. 
-Triggers on ACSP are handled differently than in OLS so the driver needs to be updated to match that
-The triggers need to be tested

**Comment by alexnorell** [comment]
Starting work on this in branch trigger

**Comment by alexnorell** [comment]
Completed
