### ISSUE TITLE
Fix "sr: [32:37.199808] acsp: Failed to set default samplerate (200000)."

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#26]
What Happens:
The sample rate is not being updated on ACSP sigrok driver
What is expected:
The sample rate should be able to be updated
How to reproduce:
-open sigrok pulseview with "-l 4" option to set log level high
-select ACSP
-press scan for devices buttong

The error will show up on the CLI showing sample rate set failure

**Comment by alexnorell** [comment]
Fixed
