### ISSUE TITLE
Unable to get second capture

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#27]
**What happens:**
On second capture no data is ever returned
**What should happen:**
Data should be returned
**How to repeat issue:**
-get a first capture
-attempt to get a second capture

**Comment by ColePBryan** [comment]
Either the unit is getting stuck in a state, or the trigger is not getting set. Pretty sure this is a ACSP issue and not the driver.

**Comment by ColePBryan** [comment]
If you re-load the driver then it gets a capture. So this could be a driver issue, perhaps not sending enough bytes to complete the command send. Or for some reason reloading the driver gets the ACSP into a stable state.

**Comment by alexnorell** [comment]
Fixed with current build
