### ISSUE TITLE
multitrigger doesn't work at 100Mhz

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#34]
Using channel 0,2 rising edge and channel 1 falling edge with function generator should trigger, but does not work on 100Mhz

**Comment by alexnorell** [comment]
How many stages are we going to support? Is this a FPGA thing or software issue?

**Comment by ColePBryan** [comment]
This is only one stage, but multi trigger. I think this is a hardware thing

**Comment by alexnorell** [comment]
Can we check if this still doesn't work?

**Comment by johntumath** [comment]
I have tested the multi trigger on all 8 channels at 100MHz, 20Mhz, and 100KHz, and confirm a trigger every time, as well as it never-triggering on several non-trigger conditions.
