### ISSUE TITLE
Trigger(basic) Documentation

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#7]
- module overview
- interface definitions
- module functionality
  - input requirements
  - output requirements
- inputs and outputs summary

**Comment by johntumath** [comment]
# Module: trigger_basic


### Module Overview
The trigger module looks for patterns that will begin the data capture process.  The trigger is setup by the controller with signals to `config_data` and then it is armed by envoking `arm`.  After being armed, the module envokes the `run` signal when a signal is detected, alerting the controller module to begin the capture sequence. The basic trigger starts capture on any channel signal specified by the controller. A more advanced trigger would have more selection options for when to trigger.

### Module Interfaces

##### Input Requirements
#
Signal Name | Width | Signal Description
--------------------- | ----------------------------- | -------------------------------------------------------------------------------------------
clock | 1 | System Clock
reset | 1 | System Reset
validin | 1 | Specifies if the data being passed through is valid.
dataIn | SAMPLE_WIDTH | Sample data (paramaterized)
config_data | TBD | Configuration parameters from controller
arm | 1 | Signal from Controller, arming the trigger.



##### Output Requirements
#
Signal Name | Width | Signal Description
--------------------- | ----------------------------- | -------------------------------------------------------------------------------------------
run | 1 | Tells controller when trigger hit.

#### Design Considerations

The module is paramaterized to allow for larger channel sizes in the future alongside an expandable control system for trigger detection.
`SAMPLE_WIDTH` is set to a default of 8 bits.

#### Test Plan

Unit testing of the module ensures that the `run` signal is envoked if and only if the proper arming procedure is followed and only if a valid `dataIn` is given to the module.

#7

**Comment by ColePBryan** [comment]
@johntumath is this in documentation anywhere or just as a comment?

**Comment by alexnorell** [comment]
It can be moved into the documentation repo

**Comment by johntumath** [comment]
It also needs to be updated with falling/rising edge signals.
